### ISSUE TITLE
Try out different application types

### ISSUE THREAD

**Issue by TiiKoh** [TiiKoh/TeamSkyNet#11]
What works, what doesn't work, what seems like a good option to use?

**Comment by nataliehi** [comment]
Django requires extra package download, not specified on their website. Couldn't quite get the tutorial app to work as expected

**Comment by nataliehi** [comment]
Flask tutorial works at least

**Comment by TiiKoh** [comment]
I say we just use Python, Django and Flask feel a little bit overwhelming to me, at least for now. The attempt.py you submitted seems like a really good start.

**Comment by nataliehi** [comment]
Fair enough, shall we close this issue?
