### ISSUE TITLE
Figure out how to make multi-word queries

### ISSUE THREAD

**Issue by TiiKoh** [TiiKoh/TeamSkyNet#13]
For example, "Anna Puu", what to do if user input is several words?

**Comment by TiiKoh** [comment]
Solved, modified attempt.py (added a new function fixQuery()). There was probably a fancy way to address a particular issue/ticket in Git when doing a push, but I forgot how to do that.

**Comment by DmitryKey** [comment]
@TiiKoh to address a particular issue, use the syntax in your commit message: #13 and the commit will be attached to the respective issue (13).
